using System.IO;
using System.Security.Cryptography;

namespace NexusApp.Services;

// The pure trust core of the updater: pinned public key, signature verify, hash compare,
// strict version comparison. No I/O except FileHashMatches's read, no network, no WPF, so
// every security property is provable in unit tests with an in-test keypair.
public static class UpdateVerifier
{
    // The ONLY key update manifests are accepted from. This is the PUBLIC half (safe to
    // publish); the private half lives offline on the maintainer's machine and is never in
    // the repo or CI. Generated by scripts/generate_update_keys.ps1. Anything that does not
    // verify against this key fails SAFE: no update is ever offered.
    public const string PublicKeyPem = """
        -----BEGIN PUBLIC KEY-----
        MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEhAlq6J380DEOtRoib5V09wKiXrfT
        kydDyYCCvjw6Bv8XJsk2nmZl0hWT50XZoDvEA3gzmGaIB60rq8SZ2ot8Iw==
        -----END PUBLIC KEY-----
        """;

    /// <summary>Verify an update manifest's detached signature against the compiled-in key.</summary>
    public static bool VerifySignature(byte[] manifestBytes, byte[] signature) =>
        VerifySignature(manifestBytes, signature, PublicKeyPem);

    // Test seam: same code path, caller-supplied key. Any crypto-layer complaint (bad PEM,
    // wrong-length signature) is a verification FAILURE, not an exception: fail closed.
    internal static bool VerifySignature(byte[] manifestBytes, byte[] signature, string publicKeyPem)
    {
        if (manifestBytes is null || signature is null) return false;
        try
        {
            using var ecdsa = ECDsa.Create();
            ecdsa.ImportFromPem(publicKeyPem);
            return ecdsa.VerifyData(manifestBytes, signature, HashAlgorithmName.SHA256);
        }
        catch { return false; }
    }

    // Constant-time compare so a hash check can never become a timing oracle. Overkill for
    // a public artifact, but it costs nothing and matches the fail-closed posture.
    internal static bool HashMatches(string? hexExpected, byte[]? actualHash)
    {
        if (string.IsNullOrEmpty(hexExpected) || actualHash is null) return false;
        byte[] expected;
        try { expected = Convert.FromHexString(hexExpected); }
        catch (FormatException) { return false; }
        return CryptographicOperations.FixedTimeEquals(expected, actualHash);
    }

    /// <summary>SHA-256 the file at path and compare to the manifest's expected hex hash.</summary>
    public static bool FileHashMatches(string path, string hexExpected)
    {
        using var fs = File.OpenRead(path);
        return HashMatches(hexExpected, SHA256.HashData(fs));
    }

    // Strictly-greater version rule: kills downgrades and same-version reinstall loops in
    // one place. Unparseable input on either side is false (never guess about versions).
    internal static bool IsUpgrade(string? current, string? candidate)
    {
        if (!Version.TryParse(current, out var cur)) return false;
        if (!Version.TryParse(candidate, out var cand)) return false;
        return cand > cur;
    }
}
